# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: 首页
    link: /
  - name: 文章
    submenu:
      - name: 日常
        link: /update/2020/06/24/daily-life.html
      - name: 儿童节
        link: /update/2020/06/19/children-day.html
      - name: 关于我
        link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/pajir
